//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Club
    {
        public int ClubID { get; set; }
        public string ClubName { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
    
        public virtual MemberShip MemberShip { get; set; }
        public virtual President President { get; set; }
        public virtual Center Center { get; set; }
    }
}
